name: kipik_v4
description: Nouvelle application KIPIK V4 pour la gestion de projets tatouage.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.9.5
  vibration: ^3.1.3

  # Localisation
  easy_localization: ^3.0.7

  # State management
  provider: ^6.1.1

  # Audio / vidéo / animations
  just_audio: ^0.10.1
  lottie: ^3.3.1

  # Map & géoloc
  flutter_map: ^8.1.1
  geolocator: ^14.0.0
  latlong2: ^0.9.0

  # Screenshot, fichiers
  screenshot: ^3.0.0
  file_selector: ^1.0.3
  path_provider: ^2.1.2

  # Réseaux & environnement
  flutter_dotenv: ^5.0.2
  http: ^1.1.0
  uuid: ^4.0.0
  url_launcher: ^6.1.10

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  firebase_crashlytics: ^4.3.5
  firebase_analytics: ^11.4.5
  firebase_remote_config: ^5.4.3
  cloud_functions: ^5.5.0 

  # Stripe
  flutter_stripe: ^11.5.0
  stripe_android: ^11.5.0
  stripe_ios: ^11.5.0


  # Typo
  google_fonts: ^6.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_kipik.png
    - assets/logo_k.ico
    - assets/background_charbon.png
    - assets/background1.png
    - assets/background2.png
    - assets/background3.png
    - assets/background4.png
    - assets/animation_loader.gif
    - assets/marker_machine.png
    - assets/marker_tattoo_machine.png
    - assets/k.png
    - assets/videos/animation_background.mp4
    - assets/sounds/tattoo_machine.mp3
    - assets/translations/en.json
    - assets/translations/fr.json
    - assets/translations/de.json
    - assets/translations/es.json
    - assets/fonts/PermanentMarker-Regular.ttf
    - assets/avatars/avatar1.jpg
    - assets/avatars/avatar2.jpg
    - assets/avatars/avatar3.jpg
    - assets/avatars/avatar4.jpg
    - assets/avatars/avatar5.jpg
    - assets/avatars/avatar_assistant_kipik.png
    - assets/avatars/avatar_neutre.png
    - assets/avatars/avatar_user_neutre.png
    - assets/avatar_zones.png

  fonts:
    - family: PermanentMarker
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf
